name = input("What is your name?\n")
print("My name is", name,".")
age = int(input("How old are you?\n"))
print("I'm", age, "years old.")
gpa = float(input("what is your graduation cgpa?\n"))
print("My cgpa of BBA is", gpa,".")